name: Nitro Deploy
description: Nitro Deploy speeds server.
author: productdevbook <hi@productdevbook.com>

branding:
  color: orange
  icon: cloud-lightning

inputs:
  TOKEN:
    required: true
    description: The Nitro Deploy token to use to authenticate with the Nitro Deploy API.
  AUTO_BUILD:
    required: false
    default: 'false'
    description: Whether to automatically build your project before deploying. Defaults to `false`.
  EXPORT_FOLDER:
    required: false
    default: .output
    description: The folder to export to Nitro Deploy. Defaults to the current working directory.
  BUILD_COMMAND:
    required: false
    default: npm run build
    description: The command to run to build your project. Defaults to `npm run build`.
  TAG:
    required: false
    default: github
    description: The tag to use when pushing to Nitro Deploy. Defaults to `github`.

runs:
  using: node20
  main: dist/index.js
